controllers_client:
    resource: ../../src/Infrastructure/API/Common/V1/Client/Controller/
    type: annotation

controllers_secure:
    resource: ../../src/Infrastructure/API/Common/V1/Notification/Controller/
    type: annotation

kernel:
    resource: ../../src/Infrastructure/Kernel.php
    type: annotation
